# This compose file can be optionally supplied for rancher
# It includes some optimizations like qgis-server load balancer and multiple
# scaling for celery and qgis-server-backend
version: '2'
services:
  qgis-server:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: qgis-server
        priority: 1
        protocol: http
        service: qgis-server-backend
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  celery:
    scale: 4
    start_on_create: true
  django:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true
  inasafe-headless-analysis:
    scale: 4
    start_on_create: true
  inasafe-headless:
    scale: 4
    start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
  qgis-server-backend:
    scale: 4
    start_on_create: true
  postgis:
    scale: 1
    start_on_create: true
